backend:
  name: git-gateway
media_folder: static/assets
public_folder: assets
collections:
  - name: basic-deliverable
    label: Photo and Text Deliverable
    folder: cmsContent/deliverables/basics
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image, required: false }
      - { name: body, label: Content, widget: markdown }
      - {
          name: priority,
          label: Priority,
          widget: number,
          hint: "Posts will be ordered first by this number (higher numbers appear further up the page) and secondarily by their published date.",
          default: 0,
        }
      - { name: publishedDate, label: Published, widget: datetime }
  - name: video-deliverable
    label: Video Deliverable
    folder: cmsContent/deliverables/videos
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - {
          name: videoLink,
          label: "Vimeo Video #",
          widget: string,
          hint: "Copy the #ID from the end of the link and paste here. (eg. 399659174)",
        }
      - {
          name: priority,
          label: Priority,
          widget: number,
          hint: "Posts will be ordered first by this number (higher numbers appear further up the page) and secondarily by their published date.",
          default: 0,
        }
      - { name: publishedDate, label: Published, widget: datetime }
  - name: quote-deliverable
    label: Quote Deliverable
    folder: cmsContent/deliverables/quotes
    create: true
    editor:
      preview: false
    fields:
      - {
          name: title,
          label: "Name and Position",
          hint: "In the following format: Jason, NHS Clinician",
        }
      - { name: quote, label: "Quote", widget: text }
      - {
          name: priority,
          label: Priority,
          widget: number,
          hint: "Posts will be ordered first by this number (higher numbers appear further up the page) and secondarily by their published date.",
          default: 0,
        }
      - { name: publishedDate, label: Published, widget: datetime }
  - name: blog
    label: News Post
    folder: cmsContent/blogs
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: "Title" }
      - { name: minutes, label: "Minutes to read article", widget: number }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Content, widget: markdown }
      - { name: publishedDate, label: Published, widget: datetime }
  - name: site-information
    label: Site Information
    files:
      - label: "Amount Raised"
        name: "amount-raised"
        file: "cmsContent/siteInformation/amountRaised.yml"
        identifier_field: amountRaised
        fields:
          - { name: amountRaised, label: "Amount Raised" }
